import { useState } from 'react';
import type { SuccessfulScrape } from '../../types/nessie';
import type { Batch } from '../../hooks/useBatches';
import { LoadingSkeleton } from './LoadingSkeleton';

interface LeadDetailProps {
  lead: SuccessfulScrape | null;
  batch: Batch | null;
  loading?: boolean;
  onToast: (message: string) => void;
}

export const LeadDetail = ({ lead, batch, loading, onToast }: LeadDetailProps) => {
  const [messageSubject, setMessageSubject] = useState('');
  const [messageBody, setMessageBody] = useState('');

  if (loading) {
    return <LoadingSkeleton />;
  }

  if (!lead || !batch) {
    return (
      <div className="no-lead-selected">
        Select a lead from the left to see details and generate an outreach message.
      </div>
    );
  }

  const mergeTemplate = (template: string, lead: SuccessfulScrape): string => {
    const name = 'there';
    return template
      .replace(/\{\{\s*name\s*\}\}/gi, name)
      .replace(/\{\{\s*company\s*\}\}/gi, lead.company || '')
      .replace(/\{\{\s*industry\s*\}\}/gi, lead.industry || '')
      .replace(/\{\{\s*icebreaker\s*\}\}/gi, lead.icebreaker || '')
      .replace(/\{\{\s*website\s*\}\}/gi, lead.website || '');
  };

  const subject = mergeTemplate(batch.subject_template || '', lead);
  const body = mergeTemplate(batch.body_template || '', lead);

  if (messageSubject === '' && subject) setMessageSubject(subject);
  if (messageBody === '' && body) setMessageBody(body);

  const copyToClipboard = (text: string) => {
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(text);
    } else {
      const textarea = document.createElement('textarea');
      textarea.value = text;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
    }
    onToast('Copied to clipboard');
  };

  return (
    <div>
      <div className="section">
        <div className="section-header">
          <div className="section-title">Lead Summary</div>
          <div className="section-tag">
            current lead · from batch {batch.label}
          </div>
        </div>
        <div className="card">
          <div className="lead-grid">
            <div>
              <div className="label">Website</div>
              <div className="value">
                <a href={lead.website} target="_blank" rel="noreferrer">
                  {lead.website}
                </a>
              </div>
            </div>
            <div>
              <div className="label">Email</div>
              <div className="value">
                {Array.isArray(lead.emails) && lead.emails.length > 0
                  ? lead.emails[0]
                  : 'No email'}
              </div>
            </div>
            <div>
              <div className="label">Industry</div>
              <div className="value">
                <span className="pill-inline">{lead.industry || 'business'}</span>
              </div>
            </div>
            <div>
              <div className="label">Owner</div>
              <div className="value">Assigned to Nessie user</div>
            </div>
          </div>
        </div>
      </div>

      <div className="section">
        <div className="section-header">
          <div className="section-title">Icebreaker</div>
          <div className="section-tag">generated by Nessie</div>
        </div>
        <div className="card">
          <div className="icebreaker-text">{lead.icebreaker}</div>
        </div>
      </div>

      <div className="section">
        <div className="section-header">
          <div className="section-title">Message</div>
          <div className="section-tag">template + placeholders merged</div>
        </div>
        <div className="card">
          <div style={{ marginBottom: '8px' }}>
            <div className="label">Subject</div>
            <input
              className="input"
              value={messageSubject}
              onChange={(e) => setMessageSubject(e.target.value)}
            />
          </div>
          <div>
            <div className="label">Body</div>
            <textarea
              className="textarea"
              value={messageBody}
              onChange={(e) => setMessageBody(e.target.value)}
            />
            <div className="helper-text">
              Generated from your batch template. Edit freely before sending.
            </div>
          </div>
          <div className="button-row">
            <button className="btn" onClick={() => copyToClipboard(messageSubject)}>
              Copy subject
            </button>
            <button
              className="btn secondary"
              onClick={() => copyToClipboard(messageBody)}
            >
              Copy body
            </button>
            <button
              className="btn ghost"
              onClick={() =>
                copyToClipboard(`Subject: ${messageSubject}\n\n${messageBody}`)
              }
            >
              Copy full message
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
