import { useState } from 'react';
import type { SuccessfulScrape } from '../../types/nessie';
import type { Batch } from '../../hooks/useBatches';
import { LoadingSkeleton } from './LoadingSkeleton';

interface LeadDetailProps {
  lead: SuccessfulScrape | null;
  batch: Batch | null;
  loading?: boolean;
  onToast: (message: string) => void;
}

export const LeadDetail = ({ lead, batch, loading, onToast }: LeadDetailProps) => {
  const [messageSubject, setMessageSubject] = useState('');
  const [messageBody, setMessageBody] = useState('');

  console.log('[LeadDetail] Rendering. Loading:', loading, 'Lead:', lead?.id, 'Batch:', batch?.id);

  if (loading) {
    console.log('[LeadDetail] Showing loading skeleton');
    return <LoadingSkeleton />;
  }

  if (!lead || !batch) {
    console.log('[LeadDetail] No lead or batch selected');
    return (
      <div className="no-lead-selected">
        Select a lead from the left to see details and generate an outreach message.
      </div>
    );
  }

  console.log('[LeadDetail] Displaying lead:', lead.company, lead.domain);

  const defaultSubject = `Quick idea for ${lead.company || lead.domain}`;
  const defaultBody = `Hey there,

${lead.icebreaker || 'I noticed your business online.'}

Many ${lead.industry || 'businesses'} lose potential work because follow ups depend on whoever's available at the time. A simple automation layer keeps every enquiry answered, quotes followed up, and appointments booked, all without adding extra admin.

Worth a quick chat this week to see how that setup could work for your team?

Kind regards,
Sami
Kelpie AI × Especial Agency`;

  if (messageSubject === '' && defaultSubject) setMessageSubject(defaultSubject);
  if (messageBody === '' && defaultBody) setMessageBody(defaultBody);

  const copyToClipboard = (text: string) => {
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(text);
    } else {
      const textarea = document.createElement('textarea');
      textarea.value = text;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
    }
    onToast('Copied to clipboard');
  };

  return (
    <div>
      <div className="section">
        <div className="section-header">
          <div className="section-title">Lead Summary</div>
          <div className="section-tag">
            current lead · from batch {batch.label}
          </div>
        </div>
        <div className="card">
          <div className="lead-grid">
            <div>
              <div className="label">Website</div>
              <div className="value">
                <a href={lead.website} target="_blank" rel="noreferrer">
                  {lead.website}
                </a>
              </div>
            </div>
            <div>
              <div className="label">Email</div>
              <div className="value">
                {Array.isArray(lead.emails) && lead.emails.length > 0
                  ? lead.emails[0]
                  : 'No email'}
              </div>
            </div>
            <div>
              <div className="label">Industry</div>
              <div className="value">
                <span className="pill-inline">{lead.industry || 'business'}</span>
              </div>
            </div>
            <div>
              <div className="label">Owner</div>
              <div className="value">Assigned to Nessie user</div>
            </div>
          </div>
        </div>
      </div>

      <div className="section">
        <div className="section-header">
          <div className="section-title">Icebreaker</div>
          <div className="section-tag">generated by Nessie</div>
        </div>
        <div className="card">
          <div className="icebreaker-text">{lead.icebreaker}</div>
        </div>
      </div>

      <div className="section">
        <div className="section-header">
          <div className="section-title">Message</div>
          <div className="section-tag">auto-generated outreach message</div>
        </div>
        <div className="card">
          <div style={{ marginBottom: '8px' }}>
            <div className="label">Subject</div>
            <input
              className="input"
              value={messageSubject}
              onChange={(e) => setMessageSubject(e.target.value)}
            />
          </div>
          <div>
            <div className="label">Body</div>
            <textarea
              className="textarea"
              value={messageBody}
              onChange={(e) => setMessageBody(e.target.value)}
            />
            <div className="helper-text">
              Auto-generated message based on lead details. Edit freely before sending.
            </div>
          </div>
          <div className="button-row">
            <button className="btn" onClick={() => copyToClipboard(messageSubject)}>
              Copy subject
            </button>
            <button
              className="btn secondary"
              onClick={() => copyToClipboard(messageBody)}
            >
              Copy body
            </button>
            <button
              className="btn ghost"
              onClick={() =>
                copyToClipboard(`Subject: ${messageSubject}\n\n${messageBody}`)
              }
            >
              Copy full message
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
